## 03 — Integrating Eye-Tracking Data and Stimulus Metadata

In [ ]:
### Merge observations with experimental stimulus information

In [45]:
import pandas as pd
from pathlib import Path

In [47]:
#Get the main project folder (moves up from 'notebooks' to root) ->Python_eye_tracking_2x2
project_folder = Path.cwd().parent

In [49]:
# Construct the correct path to the interim folder
csv_file_path = project_folder / "data" / "interim" / "results_binned_02.csv"

In [51]:
#Read the dataset into pandas
results_binned_02 = pd.read_csv(csv_file_path)

In [53]:
results_binned = results_binned_02.copy()

In [55]:
print(results_binned.shape)

(371510, 15)

In [57]:
print(results_binned.head())

  ParticipantName    items  Lists  RecordingTimestamp  time_diff  \
0          part05  Item12c  List2              139899          0
1          part05  Item12c  List2              139907          8
2          part05  Item12c  List2              139915         16
3          part05  Item12c  List2              139924         25
4          part05  Item12c  List2              139932         33

   GazeEventDur_ms Validity left Validity right EyeMovementType  GazePointX  \
0              225         Valid          Valid        Fixation       477.0
1              225         Valid          Valid        Fixation       482.0
2              225         Valid          Valid        Fixation       476.0
3              225         Valid          Valid        Fixation       485.0
4              225         Valid          Valid        Fixation       495.0

   GazePointY   AOI  item_onset_time  ms  bin20
0       442.0  left           139899   0    0.0
1       437.0  left           139899   8    0.0
2       435.0  left           139899  16   20.0
3       434.0  left           139899  25   20.0
4       454.0  left           139899  33   40.0

In [59]:
# The metadata shoudl be loaded separately:
stimuli = pd.read_csv(
    project_folder / "data" / "metadata" / "NomDat_experimental_stimuli.csv", sep=";"
)

In [61]:
stimuli.shape
stimuli.head()

,lists,Item,pronoun,pron_cond,svo_ovs,type,audio,Pictures,FirstMention,subj_image,obj_image,middle_image,image_left,image_middle,image_right,sentences
0,list1,Item04d,ihn,obj_pron,ovs,critical,item04d.wav,l_r,left,penguin,parrot,zoo,penguin,zoo,parrot,თუთიყუშს ეალერსება პინგვინი ზოოპარკის კარიბჭის...
1,list1,Item17a,er,subj_pron,svo,critical,item17a.wav,l_r,left,lord,fighter,fire,lord,fire,fighter,მბრძანებელი მოუწოდებს მებრძოლს ცეცხლთან ბრძოლი...
2,list1,Item09c,er,subj_pron,ovs,critical,item09c.wav,l_r,left,stall,deer,road,stall,road,deer,ირემს მიერეკება ჯიხვი გზაზე. ის ფიქრობს რომ მა...
3,list1,Item02b,ihn,obj_pron,svo,critical,item02b.wav,r_l,right,bull,elephant,desert,elephant,desert,bull,ხარი იცავს სპილოს უდაბნოში. მას აწუხებს სიცხე.
4,list1,Item19c,er,subj_pron,ovs,critical,item19c.wav,l_r,left,eagle,ostrich,hut,eagle,hut,ostrich,არწივი მიყავს სირაქლემას ქოხამდე. ის არის აღ...

In [63]:
# to make the join key consistent the column name shout match
stimuli = stimuli.rename(
    columns={"Item": "items"}
)

In [65]:
results_binned.head()

,ParticipantName,items,Lists,RecordingTimestamp,time_diff,GazeEventDur_ms,Validity left,Validity right,EyeMovementType,GazePointX,GazePointY,AOI,item_onset_time,ms,bin20
0,part05,Item12c,List2,139899,0,225,Valid,Valid,Fixation,477.0,442.0,left,139899,0,0.0
1,part05,Item12c,List2,139907,8,225,Valid,Valid,Fixation,482.0,437.0,left,139899,8,0.0
2,part05,Item12c,List2,139915,16,225,Valid,Valid,Fixation,476.0,435.0,left,139899,16,20.0
3,part05,Item12c,List2,139924,25,225,Valid,Valid,Fixation,485.0,434.0,left,139899,25,20.0
4,part05,Item12c,List2,139932,33,225,Valid,Valid,Fixation,495.0,454.0,left,139899,33,40.0

In [67]:
stimuli.head()

,lists,items,pronoun,pron_cond,svo_ovs,type,audio,Pictures,FirstMention,subj_image,obj_image,middle_image,image_left,image_middle,image_right,sentences
0,list1,Item04d,ihn,obj_pron,ovs,critical,item04d.wav,l_r,left,penguin,parrot,zoo,penguin,zoo,parrot,თუთიყუშს ეალერსება პინგვინი ზოოპარკის კარიბჭის...
1,list1,Item17a,er,subj_pron,svo,critical,item17a.wav,l_r,left,lord,fighter,fire,lord,fire,fighter,მბრძანებელი მოუწოდებს მებრძოლს ცეცხლთან ბრძოლი...
2,list1,Item09c,er,subj_pron,ovs,critical,item09c.wav,l_r,left,stall,deer,road,stall,road,deer,ირემს მიერეკება ჯიხვი გზაზე. ის ფიქრობს რომ მა...
3,list1,Item02b,ihn,obj_pron,svo,critical,item02b.wav,r_l,right,bull,elephant,desert,elephant,desert,bull,ხარი იცავს სპილოს უდაბნოში. მას აწუხებს სიცხე.
4,list1,Item19c,er,subj_pron,ovs,critical,item19c.wav,l_r,left,eagle,ostrich,hut,eagle,hut,ostrich,არწივი მიყავს სირაქლემას ქოხამდე. ის არის აღ...

In [69]:
et_data_joined = results_binned.merge(
    stimuli,
    on="items",
    how="left"
)

In [71]:
et_data_joined.head()

,ParticipantName,items,Lists,RecordingTimestamp,time_diff,GazeEventDur_ms,Validity left,Validity right,EyeMovementType,GazePointX,...,audio,Pictures,FirstMention,subj_image,obj_image,middle_image,image_left,image_middle,image_right,sentences
0,part05,Item12c,List2,139899,0,225,Valid,Valid,Fixation,477.0,...,item12c.wav,l_r,left,hawk,fox,trees,hawk,trees,fox,მელას დასცინის ქორი ხეებს შორის. ის არის გაბრ...
1,part05,Item12c,List2,139907,8,225,Valid,Valid,Fixation,482.0,...,item12c.wav,l_r,left,hawk,fox,trees,hawk,trees,fox,მელას დასცინის ქორი ხეებს შორის. ის არის გაბრ...
2,part05,Item12c,List2,139915,16,225,Valid,Valid,Fixation,476.0,...,item12c.wav,l_r,left,hawk,fox,trees,hawk,trees,fox,მელას დასცინის ქორი ხეებს შორის. ის არის გაბრ...
3,part05,Item12c,List2,139924,25,225,Valid,Valid,Fixation,485.0,...,item12c.wav,l_r,left,hawk,fox,trees,hawk,trees,fox,მელას დასცინის ქორი ხეებს შორის. ის არის გაბრ...
4,part05,Item12c,List2,139932,33,225,Valid,Valid,Fixation,495.0,...,item12c.wav,l_r,left,hawk,fox,trees,hawk,trees,fox,მელას დასცინის ქორი ხეებს შორის. ის არის გაბრ...

In [73]:
# Create an independent copy of et_data_joined
et_data_joined_03 = et_data_joined.copy()

In [75]:
from pathlib import Path

# Define the interim output path
interim_folder = project_folder / "data" / "interim"
# Define the file path
csv_file_path = interim_folder / "et_data_joined_03.csv"
# Export to CSV
et_data_joined_03.to_csv(csv_file_path, index=False)

In [76]:
# End of the inspection and checking and merging the eye-tracking file with the metadata. The next step is to structure the data for analysis.

## Merge validation: 
All 80 unique stimulus IDs in the eye-tracking dataset matched the stimulus metadata. No unmatched eye-tracking stimulus IDs were detected. The merge preserved the total number of rows (371,510), indicating that the integration did not change the dataset's row count.